=== rmadhuram/QuizShow/data/cci-retreat-2011/quiz.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSPY v5 rel. 2 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="answer" type="xs:string"/>
	<xs:element name="points">
		<xs:complexType>
			<xs:attribute name="values" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="qa">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="question"/>
				<xs:element ref="answer"/>
				<xs:element name="audioclip" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="file" type="xs:string" use="required"/>
						<xs:attribute name="leadtime" type="xs:int" use="optional" default="0"/>
						<xs:attribute name="startTime" type="xs:int" use="optional"/>
						<xs:attribute name="endTime" type="xs:int" use="optional"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="masterNotes" type="xs:string" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="image" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="question" type="xs:string"/>
	<xs:element name="questions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="qa" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="quiz">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="round" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="round">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="points"/>
				<xs:element ref="section" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="section">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="questions"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== rmadhuram/QuizShow/data/quiz05/quiz.xml
<quiz xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="quiz.xsd">
	<round>
		<points values="100,200,300,400,500"/>
		<section id="1" name="Anagrams">
			<questions>
				<qa>
					<question><![CDATA[First five books: PEANUT TECH]]></question>
					<answer><![CDATA[PEANUT TECH == PENTATEUCH]]></answer>
				</qa>
				<qa>
					<question><![CDATA[He prophesised the destruction of Nineveh: HUMAN]]></question>
					<answer><![CDATA[HUMAN == NAHUM]]></answer>
				</qa>
				<qa>
					<question><![CDATA[Long live! : HEALTH MUSE]]></question>
					<answer><![CDATA[HEALTH MUSE == METHUSELAH]]></answer>
				</qa>
				<qa>
					<question><![CDATA[This is set on fire by hell: GO TUNE]]></question>
					<answer><![CDATA[GO TUNE == TONGUE (James 3:6)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[Bring out the meaning: SIX GEESE]]></question>
					<answer><![CDATA[SIX GEESE == EXEGESIS]]></answer>
				</qa>
			</questions>
		</section>
		<section id="2" name="Musical Instruments">
			<questions>
				<qa>
					<question><![CDATA[David and the whole house of Israel were singing songs and playing many musical instruments while transporting this.]]></question>
					<answer><![CDATA[The ark of the covenent (II Samuel 6:5)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[In the time of Daniel, people of Babylon had to do this when they heard the sound of many musical instruments.]]></question>
					<answer><![CDATA[bow down and worship the golden image (Daniel 3:5)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[After David had killed the Philistine, the women danced and sang with these instruments]]></question>
					<answer><![CDATA[Tambourines and lutes (triangles) (I Samuel 18:6)]]></answer>
				</qa>
				<qa image="images/kinnor.jpg">
					<question><![CDATA[David's harp had ten strings as shown here. It is commonly known as this]]></question>
					<answer><![CDATA[Kinnor]]></answer>
				</qa>
				<qa>
					<question><![CDATA[This instrument, made of ram's horn was blown during important events,]]></question>
					<answer><![CDATA[Shofar]]></answer>
				</qa>
			</questions>
		</section>
		<section id="3" name="Who said it?">
			<questions>
				<qa>
					<question><![CDATA["But even if He does not, we want you to know, O king, that we will not serve your gods or worship the image of gold you have set up."]]></question>
					<answer><![CDATA[Shadrach, Meshach and Abednego (Daniel 3:18)]]></answer>
				</qa>
				<qa>
					<question><![CDATA["You brood of vipers! Who warned you to flee from the coming wrath?"]]></question>
					<answer><![CDATA[John the baptist (Matt 3:7)]]></answer>
				</qa>
				<qa>
					<question><![CDATA["your sister-in-law is going back to her people and her gods. Go back with her."]]></question>
					<answer><![CDATA[Naomi (Ruth 1:15)]]></answer>
				</qa>
				<qa>
					<question><![CDATA["There is a lion outside!", "I will be murdered in the streets!" ]]></question>
					<answer><![CDATA[The sluggard (Prov 22:13)]]></answer>
				</qa>
				<qa>
					<question><![CDATA["Leave these men alone! Let them go! For if their purpose or activity is of human origin, it will fail. But if it is from God, you will not be able to stop these men;"]]></question>
					<answer><![CDATA[Gamaliel (Acts 5:38,39)]]></answer>
				</qa>
			</questions>
		</section>
		<section id="4" name="Water water everywhere">
			<questions>
				<qa>
					<question><![CDATA[This place is called such because its water was bitter]]></question>
					<answer><![CDATA[Marah (Ex 15:23)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[After this man drank from a God given spring called "En Hakkore", his strength returned.]]></question>
					<answer><![CDATA[Samson (Judges 15:19)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[The Psalmist writes "I tested you at the waters of ___"]]></question>
					<answer><![CDATA[Meribah (Psalm 81:7)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[These men broke through the Philistine lines to get water for David who was very thirsty]]></question>
					<answer><![CDATA[three mighty men (Abishai, Benaiah and unnamed) II Samuel 23:16]]></answer>
				</qa>
				<qa>
					<question><![CDATA[Peter compares false prophets to these. Blackest darkness is reserved for them]]></question>
					<answer><![CDATA[springs without water  (II Peter 2:17)]]></answer>
				</qa>
			</questions>
		</section>
	</round>
	
	<round>
		<points values="100,200,300,400,500"/>
		<section id="1" name="Wine">
			<questions>
				<qa>
					<question><![CDATA[During this 40 year period the Israelites drank no wine]]></question>
					<answer><![CDATA[Wilderness journey ]]></answer>
				</qa>
				<qa>
					<question><![CDATA[This happens to new wine when put in old wineskins]]></question>
					<answer><![CDATA[skins burst (Mark 2:22)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[Lemuel is told in Proverbs that it is not good for people with this occupation to drink wine]]></question>
					<answer><![CDATA[Kings (Proverbs 31:4)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[The king of Susa had been drinking wine when he commanded this woman be brought out]]></question>
					<answer><![CDATA[Queen Vashti (Esther 1:10-11)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[According to Hosea, this Middle East country is famed for its wine.]]></question>
					<answer><![CDATA[Lebanon (Hosea 14:7)]]></answer>
				</qa>
			</questions>
		</section>
		<section id="2" name="Flora">
			<questions>
				<qa>
					<question><![CDATA[The dove returned to Noah's ark with this in its mouth.]]></question>
					<answer><![CDATA[Olive leaf]]></answer>
				</qa>
				<qa>
					<question><![CDATA[This man climbed a tree in order to see Jesus.]]></question>
					<answer><![CDATA[Zacchaeus]]></answer>
				</qa>
				<qa>
					<question><![CDATA[Aaron's rod that budded brought forth this type of fruit]]></question>
					<answer><![CDATA[Almonds (Num 17:8)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[Absalom was fleeing battle when he got his head caught in this type of tree]]></question>
					<answer><![CDATA[Terebinth (oak) (2 Sam 18:9)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[The men who went to spy on Cannon brought grapes, figs and these]]></question>
					<answer><![CDATA[Pomegranates (Num 13:23)]]></answer>
				</qa>
			</questions>
		</section>
		<section id="3" name="Parables">
			<questions>
				<qa>
					<question><![CDATA[The kingdom of heaven is like this seed]]></question>
					<answer><![CDATA[mustard]]></answer>
				</qa>
				<qa>
					<question><![CDATA[The man who built his house upon the sand is compared to this]]></question>
					<answer><![CDATA[he who hears God's words and does not put them into practice]]></answer>
				</qa>
				<qa>
					<question><![CDATA[The kingdom of heaven is like leaven, which a woman took and did this.]]></question>
					<answer><![CDATA[hid in three measures of meal till it was all leavened (Mat 13:33)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[The merchant sold all that he had to acquire this.]]></question>
					<answer><![CDATA[The sluggard (Prov 22:13)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[Jesus told the parable of the unforgiving servant when Peter asked him about this.]]></question>
					<answer><![CDATA[how many times should I forgive my brother? (Matt 18:21)]]></answer>
				</qa>
			</questions>
		</section>
		<section id="4" name="What comes next?">
			<questions>
				<qa>
					<question><![CDATA[Come, let us bow down in worship, let us kneel before the LORD our Maker;]]></question>
					<answer><![CDATA[for he is our God and we are the people of his pasture, the flock under his care... (Ps 95:7)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[Blessed are the meek, for they will inherit the earth.]]></question>
					<answer><![CDATA[Blessed are those who hunger and thirst for righteousness, for they will be filled. (Matt 5:6)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[Though the fig tree does not bud and there are no grapes on the vines,...and no cattle in the stalls, ]]></question>
					<answer><![CDATA[yet I will rejoice in the LORD, I will be joyful in God my Savior. (Habakkuk 3:18)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[The thief comes only to steal and kill and destroy; I have come that they may have life, and have it to the full.]]></question>
					<answer><![CDATA[I am the good shepherd. The good shepherd lays down his life for the sheep (John 10:11)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[No, in all these things we are more than conquerors through him who loved us.]]></question>
					<answer><![CDATA[For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers, neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord.(Rom 8:38-39)]]></answer>
				</qa>
			</questions>
		</section>
	</round>	
</quiz>

=== rmadhuram/QuizShow/data/barcamp/quiz.xml
<quiz xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="quiz.xsd">
    <round>
        <points values="100,200,300,400,500"/>
        <section id="1" name="Transportation">
            <questions>
                <qa>
                    <question><![CDATA[The invention of this in Sumer (in Mesapotamia) revolutionized transportation.]]></question>
                    <answer><![CDATA[Wheel]]></answer>
                </qa>
                <qa>
                    <question><![CDATA[There are more than one billion of these vehicles in the world.]]></question>
                    <answer><![CDATA[Bicycles]]></answer>
                </qa>
                <qa>
                    <question><![CDATA[Sir. Richard Branson started this company, the world's first spaceline!]]></question>
                    <answer><![CDATA[Virgin Galactic]]></answer>
                    <masterNotes>Burt Rutan - Ansari X Prize - Spaceship One</masterNotes>     
                </qa>
                <qa image="images/rocket.jpg">
                    <question><![CDATA[This person designed the vehicle shown here.]]></question>
                    <answer><![CDATA[Robert Stephenson - Rocket, the first modern steam locomotive]]></answer>
                </qa>
                <qa image="images/Buran.jpg">
                    <question><![CDATA[Identify this vehicle.]]></question>
                    <answer><![CDATA[Buran]]></answer>
                    <masterNotes>It took off once in 1989 and made automated landing</masterNotes>     
                </qa>
            </questions>
        </section>
        <section id="2" name="Landmarks">
            <questions>
                <qa image="images/land/Angkor_wat_temple.jpg">
                    <question><![CDATA[This temple complex in Cambodia was built in the 12th century]]></question>
                    <answer><![CDATA[Angkor Wat]]></answer>
                </qa>
                <qa image="images/land/burj.JPG">
                    <question><![CDATA[The name of the tallest building in the world was recently changed to this.]]></question>
                    <answer><![CDATA[Burj Khalifa]]></answer>
                    <masterNotes>In the honor of the President of UAE. Earlier it was called Burj Dubai</masterNotes>
                </qa>                
                <qa image="images/land/Uluru.JPG">
                    <question><![CDATA[Also referred to as Ayers Rock, this is the native name of the large sandstone rock seen here.]]></question>
                    <answer><![CDATA[Uluru]]></answer>
                </qa>                
                <qa image="images/land/SaintBasile.jpg">
                    <question><![CDATA[Identify this important landmark of Russia situated on the Red Square.]]></question>
                    <answer><![CDATA[St. Basil's Cathedral]]></answer>
                    <masterNotes>Also called as "The Cathedral of Intercession of Theotokos on the Moat"</masterNotes>
                </qa>                
                <qa image="images/land/KRN.jpg">
                    <question><![CDATA[This hotel seen here was scheduled to be completed in 1989, but work is still going on...]]></question>
                    <answer><![CDATA[Ryugyong Hotel]]></answer>
                    <masterNotes>in Pyongyang, N.Korea</masterNotes>
                </qa>
            </questions>
        </section>        
        <section id="3" name="Pictograms">
            <questions>
                <qa image="images/pict/split.gif">
                    <question></question>
                    <answer><![CDATA[Split Personality]]></answer>
                </qa>
                <qa image="images/pict/h2o.gif">
                    <question></question>
                    <answer><![CDATA[H2O (Water)]]></answer>
                </qa>
                <qa image="images/pict/summary.gif">
                    <question></question>
                    <answer><![CDATA[Summary]]></answer>
                </qa>
                <qa image="images/pict/link.jpg">
                    <question></question>
                    <answer><![CDATA[Missing LINK]]></answer>
                </qa>
                <qa image="images/pict/pain.gif">
                    <question></question>
                    <answer><![CDATA[Painless Operation]]></answer>
                </qa>                                                                
            </questions>
        </section>

        <section id="4" name="Potpourri">
            <questions>
                <qa>
                    <question><![CDATA[This form of music is translated as "Empty Orchestra" in Japanese.]]></question>
                    <answer><![CDATA[Karaoke]]></answer>
                </qa>
                <qa>
                    <question><![CDATA[This is the name of the highly valuable mineral found on the moon Pandora.]]></question>
                    <answer><![CDATA[Unobtanium]]></answer>
                </qa>
                <qa>
                    <question><![CDATA[This now defunct company's tagline is "Always ask why"]]></question>
                    <answer><![CDATA[Enron]]></answer>
                </qa>                
                <qa>
                    <question><![CDATA[These animals are said to account for more human deaths in Africa than any other African mammal.]]></question>
                    <answer><![CDATA[Hippopotamus ]]></answer>
                </qa>                
                <qa>
                    <question><![CDATA[One trillion terabytes is this.]]></question>
                    <answer><![CDATA[1 Yottabyte (Tera - Peta - Exa - Zetta - Yotta)]]></answer>
                    <masterNotes>1000^4 is tera, peta, exa, zetta and yotta</masterNotes>                    
                </qa>
            </questions>
        </section>
    </round>
</quiz>

=== rmadhuram/QuizShow/data/quiz03/quiz.xml
<quiz xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="quiz.xsd">
	<round>
		<points values="100,200,300,400,500"/>
		<section id="1" name="Anagrams">
			<questions>
				<qa>
					<question><![CDATA[By the rivers of this land in Shinar:<br>AN LOBBY]]></question>
					<answer><![CDATA[AN LOBBY = BABYLON]]></answer>
				</qa>
				<qa>
					<question><![CDATA[At the start: CARE INTO]]></question>
					<answer><![CDATA[CARE INTO = CREATION]]></answer>
				</qa>
				<qa>
					<question><![CDATA[A King of Egypt: MERE ASS]]></question>
					<answer><![CDATA[MERE ASS = RAMESES]]></answer>
				</qa>
				<qa>
					<question><![CDATA[Matthew 1: YOGA ENGEL]]></question>
					<answer><![CDATA[YOGA ENGEL = GENEOLOGY]]></answer>
				</qa>
				<qa>
					<question><![CDATA[Revelations: LOSE PAPACY]]></question>
					<answer><![CDATA[LOSE PAPACY= APOCALYPSE]]></answer>
				</qa>
			</questions>
		</section>
		<section id="2" name="Music">
			<questions>
				<qa image="images/keyboard.gif">
					<question><![CDATA[
Identify the composer]]></question>
					<answer><![CDATA[Handel
					
]]></answer>
					<audioclip file="sounds/mesiah44.mid" startTime="20" endTime="40"/>
					<masterNotes>blah blah</masterNotes>
				</qa>
				<qa image="images/keyboard.gif">
					<question><![CDATA[
					Identify the song]]></question>
					<answer><![CDATA[Love Lifted Me

]]></answer>
					<audioclip file="sounds/love.mid" startTime="10" endTime="40"/>
					<masterNotes>blah blah</masterNotes>
				</qa>
				<qa image="images/crystal.jpg">
					<question>This church holds one of the world's largest pipe organs</question>
					<answer><![CDATA[Crystal Cathedral

]]></answer>
					<masterNotes>blah blah</masterNotes>
				</qa>
				<qa image="images/notes_009.gif">
					<question><![CDATA[She has written more than 8000 hymns, including the one heard here.]]></question>
					<answer><![CDATA[Fanny Crosby


]]></answer>
					<audioclip file="sounds/blessed.mid" startTime="15" endTime="45"/>
					<masterNotes>It is remarkable that she was blind. Other well known hymns are Praise Him.., Tell me the story of Jesus</masterNotes>
				</qa>
				<qa image="images/notes_009.gif">
					<question><![CDATA[
					The second stanza says that the Church <br> moves like this.]]></question>
					<answer><![CDATA[A mighty army<br><br>"Like a mighty army, moves the church of God"

]]></answer>
					<audioclip file="sounds/onward.mid" startTime="0" endTime="30"/>
					<masterNotes>blah blah</masterNotes>
				</qa>
			</questions>
		</section>
		<section id="3" name="Church History">
			<questions>
				<qa>
					<question><![CDATA[This part of the Bible was written between 1-100 AD, which is called the Apostolic age.]]></question>
					<answer>The New Testament</answer>
				</qa>
				<qa>
					<question><![CDATA[This emperor set Rome on fire and murdered <br>a vast number of Christians in the <br>most cruel ways.]]></question>
					<answer>Nero</answer>
				</qa>
				<qa>
					<question><![CDATA[This ancient historian's first name is Flavius.<br>His works include "Antiquities of the Jews". ]]></question>
					<answer>Josephus</answer>
				</qa>
				<qa>
					<question><![CDATA[These places occupied by monks, usually had a <br>library and school. They were built by <br>missionaries in the middle ages.]]></question>
					<answer>Convents</answer>
				</qa>
				<qa>
					<question><![CDATA[This movement started after the invention of the <br>printing press. It was spearheaded by <br> Martin Luther and gave birth to Protestantism.]]></question>
					<answer>Reformation</answer>
				</qa>				
			</questions>
		</section>
		<section id="4" name="Bible Geography">
			<questions>
				<qa>
					<question><![CDATA[The ark came to rest on this mountain.]]></question>
					<answer>Mountains of Ararat</answer>
				</qa>
				<qa>
					<question><![CDATA[The people here were more noble.. <br>in that they received the word...<br>and searched the scriptures daily]]></question>
					<answer>Berea</answer>
				</qa>
				<qa>
					<question><![CDATA[Paul was born in this city]]></question>
					<answer>Tarsus (Acts 21:39)</answer>
				</qa>
				<qa>
					<question><![CDATA[Antipas was martyred in this city, one of the seven churches of Revelations.]]></question>
					<answer>Pergamum (Rev 2:13)</answer>
				</qa>
				<qa>
					<question><![CDATA[One of the cities of refuge, it was finally captured by Israel in 1967.]]></question>
					<answer>Golan (Heights)</answer>
				</qa>
			</questions>
		</section>
	</round>
	<round>
		<points values="100,200,300,400,500"/>
		<section id="1" name="Minerals">
			<questions>
				<qa>
					<question><![CDATA[New Jerusalem is made of this,<br> like clear glass.]]></question>
					<answer>Pure Gold (Rev 21:18)</answer>
				</qa>
				<qa>
					<question><![CDATA[The price of wisdom is beyond this.]]></question>
					<answer>Rubies (Job 15:18)</answer>
				</qa>
				<qa>
					<question><![CDATA[Isralites sang: "But You blew with Your breath,
and the sea covered them. They sank like ____ in the mighty waters."]]></question>
					<answer><![CDATA[Lead (Exodus 15:10)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[Jars made of this were filled with oil. One such jar was broken and oil was <br>poured on Jesus' head.]]></question>
					<answer>Alabaster (Luke 7:37)</answer>
				</qa>
				<qa>
					<question><![CDATA[Elisha threw this into the spring of water to purify it.]]></question>
					<answer><![CDATA[Salt (II Kings 2:21)]]></answer>
				</qa>
			</questions>
		</section>
		<section id="2" name="Crossword clues 'Z'">
			<questions>
            <qa>
               <question><![CDATA[City of God (4)]]></question>
               <answer>Zion</answer>
            </qa>
				<qa>
					<question><![CDATA[A prophet (9)]]></question>
					<answer>Zachariah, Zephaniah</answer>
				</qa>
				<qa>
					<question><![CDATA[My papa was the priest of Midian (8)]]></question>
					<answer><![CDATA[Zipporah (Exodus 2:16)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[Jesus called my sons James and John: <br> Boanerges, that is sons of thunder. (7)]]></question>
					<answer>Zebedee (Matthew 4:21)</answer>
				</qa>
				<qa>
					<question><![CDATA[These were giants, as tall as the Anakim (9)]]></question>
					<answer><![CDATA[Zamzummim (Deut 2:20)]]></answer>
				</qa>
			</questions>
		</section>
		<section id="3" name="Names of God">
			<questions>
				<qa>
					<question><![CDATA[God will provide]]></question>
					<answer><![CDATA[Jehovah Jireh (Gen. 22:13-14)<br> i.e the Lord will provide a sacrifice]]></answer>
				</qa>
				<qa>
					<question><![CDATA[God the Almighty]]></question>
					<answer>El Shaddai (Gen. 17:1)</answer>
				</qa>
				<qa>
					<question><![CDATA[the Lord our righteousness]]></question>
					<answer><![CDATA[Jehovah-tsidkenu (Jer. 23:6)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[A plural and masculine term that <br> means God who creates.]]></question>
					<answer>Elohim (Gen 1:1, Gen 1:26)</answer>
				</qa>
				<qa>
					<question><![CDATA[God the Highest.]]></question>
					<answer><![CDATA[El Elyon (Gen. 14:18)]]></answer>
				</qa>
			</questions>
		</section>
		
		<section id="4" name="Miracles">
			<questions>
				<qa>
					<question><![CDATA[This man was bitten by a poisonous snake, <br>which he shook into a fire, <br>and never felt any ill effect.]]></question>
					<answer>Paul (Acts 28:3)</answer>
				</qa>
				<qa>
					<question><![CDATA[This man healed Paul from his blindness. ]]></question>
					<answer>Ananias (Acts 9:17-18)</answer>
				</qa>
				<qa>
					<question><![CDATA[This man destroyed a Philistine temple with<br> strength given by God.]]></question>
					<answer><![CDATA[Samson (Judges 16:28-29)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[This young man was sitting on a third story window<br> listening to Paul's sermon that lasted past midnight. <br>He slept, fell down and died, <br>but was made alive.]]></question>
					<answer>Eutychus (Acts 20:9)</answer>
				</qa>
				<qa>
					<question><![CDATA[This Philistine god lost its head when confronted with the ark of the covenant.]]></question>
					<answer><![CDATA[Dagon (I Sam 5:4)]]></answer>
				</qa>
			</questions>
		</section>
						
	</round>
</quiz>
