=== rmadhuram/QuizShow/data/cci-retreat-2011/quiz.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSPY v5 rel. 2 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="answer" type="xs:string"/>
	<xs:element name="points">
		<xs:complexType>
			<xs:attribute name="values" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="qa">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="question"/>
				<xs:element ref="answer"/>
				<xs:element name="audioclip" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="file" type="xs:string" use="required"/>
						<xs:attribute name="leadtime" type="xs:int" use="optional" default="0"/>
						<xs:attribute name="startTime" type="xs:int" use="optional"/>
						<xs:attribute name="endTime" type="xs:int" use="optional"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="masterNotes" type="xs:string" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="image" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="question" type="xs:string"/>
	<xs:element name="questions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="qa" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="quiz">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="round" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="round">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="points"/>
				<xs:element ref="section" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="section">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="questions"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== rmadhuram/QuizShow/data/quiz04/quiz.xml
<quiz xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="quiz.xsd">
	<round>
		<points values="100,200,300,400,500"/>
		<section id="1" name="Angels">
			<questions>
				<qa>
					<question><![CDATA[An angel rolled a stone away from here: ]]></question>
					<answer><![CDATA[A tomb (Matthew 28:2)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[Cherubim with a flaming sword guarded the way to this]]></question>
					<answer><![CDATA[The tree of life (Genesis 3:24)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[An angel told this man to send messengers to Joppa: ]]></question>
					<answer><![CDATA[Cornelius (Acts 10:3-5)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[An angel slew 185,000 soldiers from this army]]></question>
					<answer><![CDATA[Assyrian (Isaiah 37:36)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[This man saw an angel ascend in the flame of an altar:]]></question>
					<answer><![CDATA[Manoah (Judges 13:20)]]></answer>
				</qa>
			</questions>
		</section>
		<section id="2" name="Children">
			<questions>
				<qa>
					<question><![CDATA[This child was hidden at the edge of a river to avoid being killed]]></question>
					<answer><![CDATA[Moses (Ex 2:3)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[This king threatened to cut a child in half]]></question>
					<answer><![CDATA[Solomon (1 Kings 3:25)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[This child was dropped by his nurse, and was crippled for life]]></question>
					<answer><![CDATA[Mephibosheth (2 Sam 4:4)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[This child was born as his mother heard news of his father's death.]]></question>
					<answer><![CDATA[Ichabod (1Sam 4:21)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[This boy was 8 years old when he began to reign]]></question>
					<answer><![CDATA[Josiah (2Ki 22:1)]]></answer>
				</qa>
			</questions>
		</section>
		<section id="3" name="What comes before?">
			<questions>
				<qa>
					<question><![CDATA[For God did not send his Son into the world to condemn the world, 
but to save the world through him]]></question>
					<answer><![CDATA[For God so loved the world that he gave his one and only Son, that 
whoever believes in him shall not perish but have eternal life.(John 3:16)]]></answer>
				</qa>
				<qa>
					<question><![CDATA["Of the increase of his government and peace there will be no 
end..."]]></question>
					<answer><![CDATA["For to us a child is born, to us a son is given,..." (Isaiah 9:6)]]></answer>
				</qa>
				<qa>
					<question><![CDATA["and are justified freely by his grace through the redemption that 
came by Christ Jesus."]]></question>
					<answer><![CDATA["for all have sinned and fall short of the glory of God" (Romans 3:23)]]></answer>
				</qa>
				<qa>
					<question><![CDATA["Can both fresh water and salt water flow from the same spring?"]]></question>
					<answer><![CDATA["Out of the same mouth come praise and cursing. My brothers, this 
should not be." (James 3:10)]]></answer>
				</qa>
				<qa>
					<question><![CDATA["Be self-controlled and alert. Your enemy the devil prowls around 
like a roaring lion looking for someone to devour."]]></question>
					<answer><![CDATA["Cast all your anxiety on him because he cares for you." (I Peter 5:7)]]></answer>
				</qa>
			</questions>
		</section>
		<section id="4" name="What`s in a name?">
			<questions>
				<qa>
					<question><![CDATA[Father of multitude]]></question>
					<answer><![CDATA[Abraham (Genesis 17:5)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[God is salvation]]></question>
					<answer><![CDATA[Joshua]]></answer>
				</qa>
				<qa>
					<question><![CDATA[God is my Judge]]></question>
					<answer><![CDATA[Daniel]]></answer>
				</qa>
				<qa>
					<question><![CDATA[Son of the right hand]]></question>
					<answer><![CDATA[Benjamin]]></answer>
				</qa>
				<qa>
					<question><![CDATA[Father rejoices]]></question>
					<answer><![CDATA[Abigail]]></answer>
				</qa>
			</questions>
		</section>
			<section id="5" name="Proverbs">
			<questions>
				<qa>
					<question><![CDATA[The horse is made ready for the day of battle, ____]]></question>
					<answer><![CDATA[ but victory rests with the LORD. (Proverbs 21:31)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[Pride goes before destruction ____]]></question>
					<answer><![CDATA[a haughty spirit before a fall. (Proverbs 16:18) ]]></answer>
				</qa>
				<qa>
					<question><![CDATA[This is to be chosen rather than great riches]]></question>
					<answer><![CDATA[a good name (Proverbs 22:1)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[All a man's ways seem right to him: ____]]></question>
					<answer><![CDATA[but the LORD weighs the heart. (Proverbs 21:2)]]></answer>
				</qa>
				<qa>
					<question><![CDATA[According to proverbs, this separates close friends]]></question>
					<answer><![CDATA[a gossip (Proverbs 16:28)]]></answer>
				</qa>
			</questions>
		</section>	
	</round>
</quiz>

=== rmadhuram/QuizShow/quiz-archives/quiz.xml
<quiz xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="quiz.xsd">
	<round>
		<points values="100,200,300,400,500"/>
		<section id="1" name="Mother's Day">
			<questions>
				<qa>
					<question><![CDATA[She is called the mother of all <br>the living]]></question>
					<answer>Eve (Gen 3:20)</answer>
				</qa>
				<qa>
					<question><![CDATA[She was the mother of Samuel and wife of Elkanah]]></question>
					<answer>Hannah (I Samuel 1)</answer>
				</qa>		
				<qa>
					<question><![CDATA[This is the first commandment with a promise]]></question>
					<answer><![CDATA[Honor your father and your mother, so that you may live long in the land the LORD your God is giving you. Exodus 20:12, Deut 5:16, Eph 6:2]]></answer>
				</qa>
				<qa>
					<question><![CDATA[This mother of Timothy receives a special mention in Paul's letter for her faith]]></question>
					<answer>Eunice (II Timothy 1:5)</answer>
				</qa>		
				<qa>
					<question><![CDATA[Hagar is compared to Mount Sinai, but Sarah is compared to this, who is the mother of us all]]></question>
					<answer>Heavenly Jerusalem (Galatians 4:26)</answer>
				</qa>												
						
			</questions>
		</section>
		<section id="2" name="Numbers">
			<questions>
				<qa>
					<question><![CDATA[Number of the beast; <br>number of a man]]></question>
					<answer>666 (Rev 13:18)</answer>
				</qa>
				<qa>
					<question><![CDATA[Number of stones <br>David put in his pouch ]]></question>
					<answer>5 (I Samuel 17:40)</answer>
				</qa>
				<qa>
					<question><![CDATA[Number of synoptic gospels]]></question>
					<answer>3</answer>
				</qa>
				<qa>
					<question><![CDATA[Number of years Adam lived]]></question>
					<answer>930 (Gen 5:5)</answer>
				</qa>
				<qa>
					<question><![CDATA[One cubit (as in Noah's time) is approximately this many inches]]></question>
					<answer>18</answer>
				</qa>
			</questions>
		</section>
		<section id="3" name="James">
			<questions>
				<qa>
					<question>
			                     <![CDATA[It is commonly believed that His half brother wrote the book of James]]>			          
			          </question>
					<answer>
			                     Jesus
			           </answer>
				</qa>
				<qa>
					<question>
			                     <![CDATA[Due to the practical advices it gives, the book of James is also referred to as ____ of the new testament.]]>			          
			          </question>
					<answer>
			                     Proverbs
			           </answer>
				</qa>			
				
				<qa>
					<question>
			                     <![CDATA[When giving examples of praxis, that is 'faith without works is dead', James illustrates the example of Abraham along with this woman.]]>			          
			          </question>
					<answer>
			                     Rahab
			           </answer>
				</qa>									
				
				<qa>
					<question>
			                     <![CDATA[According to James, this triumphs over judgement.]]>			          
			          </question>
					<answer>
			                     Mercy
			           </answer>
				</qa>								
				
				<qa>
					<question>
			                     <![CDATA[The book of James was included in the canon during 397 AD at this council.]]>			          
			          </question>
					<answer>
			                     Council of Carthage.
			           </answer>
				</qa>		
								
			</questions>
		</section>
		<section id="4" name="What comes next?">
			<questions>
				<qa>
					<question>
			                     <![CDATA[Lord, we don't know where you are going, so how can we know the way?]]>
			                  </question>
					<answer>
			                      <![CDATA[Jesus answered, "I am the way and the truth and the life. No one comes to the Father except through me. (John 14:6)]]>
					</answer>
				</qa>
				<qa>
					<question>
			                     <![CDATA[Behold, I am coming soon! My reward is with me, and I will give to everyone according to what he has done.]]>
			                  </question>
					<answer>
			                      <![CDATA[I am the Alpha and the Omega, the First and the Last, the Beginning and the End (Rev 22:13)]]>
					</answer>
				</qa>
				<qa>
					<question>
			                     <![CDATA[This is what the LORD says, he who made the earth, the LORD who formed it and established it - the LORD is his name:]]>
			                  </question>
					<answer>
			                      <![CDATA[Call to me and I will answer you and tell you great and unsearchable things you do not know. (Jeremiah 33:3)]]>
					</answer>
				</qa>
				
				<qa>
					<question>
			                     <![CDATA[Fear the LORD, you his saints, for those who fear him lack nothing. ]]>
			                  </question>
					<answer>
			                      <![CDATA[The lions may grow weak and hungry, but those who seek the LORD lack no good thing. (Ps 34:10)]]>
					</answer>
				</qa>
				
				<qa>
					<question>
			                     <![CDATA[Do not give dogs what is sacred; do not throw your pearls to pigs. If you do, they may trample them under their feet, and then turn and tear you to pieces.]]>
			                  </question>
					<answer>
			                      <![CDATA[Ask and it will be given to you; seek and you will find; knock and the door will be opened to you. (Matthew 7:7)]]>
					</answer>
				</qa>																
			</questions>
		</section>
		<section id="5" name="Crossword clues 'A'">
			<questions>
				<qa>
					<question><![CDATA[His brother asked, "Am I my brother's keeper?" (4)]]></question>
					<answer>
			                      Abel 
			          </answer>
				</qa>
				<qa>
					<question><![CDATA[Paul saw an altar with the inscription "TO AN UNKNOWN GOD" in this city. (6)]]></question>
					<answer>
			                      Athens 
			          </answer>
				</qa>
				<qa>
					<question><![CDATA[A Title of Christ; A word used to reinforce a statement.(4)]]></question>
					<answer>
			                      Amen  (Rev 3:14)
			          </answer>
				</qa>
							<qa>
					<question><![CDATA[It doesn't mean to feel sorry for, but means a defense of faith (11)]]></question>
					<answer>
			                      Apologetics 
			          </answer>
				</qa>
							<qa>
					<question><![CDATA[He ruled over 127 provinces stretching from India to Cush (9)]]></question>
					<answer>
			                      Ahasuerus (Esther 1:1) 
			          </answer>
				</qa>							
			</questions>
		</section>
	</round>
</quiz>
